### ISSUE TITLE
配置提交CL的环境出错

### ISSUE THREAD

**Issue by xiyichan** [MabinGo/go#11]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.6 linux/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build044374660=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

按照https://taohuawu.club/golang-contribution-guide-translation这个教程中的指示下载codereview出现问题

### What did you see instead?
![image](https://user-images.githubusercontent.com/34647972/90152627-9879dc00-ddba-11ea-87df-5053b0efd44c.png)

**Comment by zaneChou1** [comment]
`go get -u golang.org/x/review/git-codereviewcodereview` 下载 git-codereview 需要外网环境，需要使用VPN翻墙

**Comment by xiyichan** [comment]
我已经配置好了外网环境了。
![image](https://user-images.githubusercontent.com/34647972/90338561-0b828d00-e01d-11ea-8653-589fdb9ae3a0.png)
可是下载codereview后，还是出现这个
![image](https://user-images.githubusercontent.com/34647972/90338583-3ff64900-e01d-11ea-9c22-d5177c4d9e43.png)
是否需要配置路径之类的

**Comment by xiyichan** [comment]
下载这个原来不用翻墙，那个git clone go官方库才需要，这个linux和windows不同的是，gopath没有自动添加在环境上面，需要手动添加上去，在教程中也有写到.
